package lexer

import "github.com/lfmexi/golalr/prattparser/types"

// LexSymbol is an implementation of the symbols.Symbol interface for symbols generated by a lexer
type LexSymbol struct {
	text   string
	ttype  types.TokenType
	line   int
	column int
	value  interface{}
}

func newLexSymbol(l *Lexer, tokenType types.TokenType, text string, additionalValue interface{}) LexSymbol {
	if l != nil {
		return LexSymbol{
			text,
			tokenType,
			l.line,
			l.column,
			additionalValue,
		}
	}
	return LexSymbol{
		text,
		tokenType,
		0,
		0,
		additionalValue,
	}
}

// Line returns the line where the Symbol where found
func (s LexSymbol) Line() int {
	return s.line
}

// Column returns the char number where the Symbol where found
func (s LexSymbol) Column() int {
	return s.column
}

// Value returns the user defined value added on lexical recognition
func (s LexSymbol) Value() interface{} {
	return s.value
}

// Text returns the text of the Symbol
func (s LexSymbol) Text() string {
	return s.text
}

// TokenType returns the type of the token that the Symbol represents
func (s LexSymbol) TokenType() types.TokenType {
	return s.ttype
}
